
[ClassVersion("1.0.0.0"), FriendlyName("cGitRepositoryBranch")]
class cGitRepositoryBranch : OMI_BaseResource
{
    [Key] String Repository;
    [Required] String BaseDirectory;
    [Required] String Branch;
};
