<#
    Workflow breaks the scoping of EAP
    
    https://technet.microsoft.com/en-us/library/hh847796.aspx

    $ErrorActionPreference
    ----------------------
        Determines how Windows PowerShell responds to a non-terminating
        error (an error that does not stop the cmdlet processing) at the
        command line or in a script, cmdlet, or provider, such as the
        errors generated by the Write-Error cmdlet. 

        You can also use the ErrorAction common parameter of a cmdlet to 
        override the preference for a specific command.
#>

Workflow Test-ErrorActionPreferenceScoping
{
    $ErrorActionPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue

    # Should be swallowed
    Write-Error -Message 'hello'

    # EAP is more specific so it should apply -- expect to see error message but not terminate
    Write-Error -Message 'hello' -ErrorAction Continue

    # EAP is more specific so it should apply -- expect to see error message and terminate
    # not showing the verbose message
    Write-Error -Message 'hello' -ErrorAction Stop
    Write-Verbose -Message 'Should not get here'
}
# SIG # Begin signature block
# MIID1QYJKoZIhvcNAQcCoIIDxjCCA8ICAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUEko7Dk+AlBbEAbD2oSyYMsPW
# anigggH3MIIB8zCCAVygAwIBAgIQEdV66iePd65C1wmJ28XdGTANBgkqhkiG9w0B
# AQUFADAUMRIwEAYDVQQDDAlTQ09yY2hEZXYwHhcNMTUwMzA5MTQxOTIxWhcNMTkw
# MzA5MDAwMDAwWjAUMRIwEAYDVQQDDAlTQ09yY2hEZXYwgZ8wDQYJKoZIhvcNAQEB
# BQADgY0AMIGJAoGBANbZ1OGvnyPKFcCw7nDfRgAxgMXt4YPxpX/3rNVR9++v9rAi
# pY8Btj4pW9uavnDgHdBckD6HBmFCLA90TefpKYWarmlwHHMZsNKiCqiNvazhBm6T
# XyB9oyPVXLDSdid4Bcp9Z6fZIjqyHpDV2vas11hMdURzyMJZj+ibqBWc3dAZAgMB
# AAGjRjBEMBMGA1UdJQQMMAoGCCsGAQUFBwMDMB0GA1UdDgQWBBQ75WLz6WgzJ8GD
# ty2pMj8+MRAFTTAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQEFBQADgYEAoK7K
# SmNLQ++VkzdvS8Vp5JcpUi0GsfEX2AGWZ/NTxnMpyYmwEkzxAveH1jVHgk7zqglS
# OfwX2eiu0gvxz3mz9Vh55XuVJbODMfxYXuwjMjBV89jL0vE/YgbRAcU05HaWQu2z
# nkvaq1yD5SJIRBooP7KkC/zCfCWRTnXKWVTw7hwxggFIMIIBRAIBATAoMBQxEjAQ
# BgNVBAMMCVNDT3JjaERldgIQEdV66iePd65C1wmJ28XdGTAJBgUrDgMCGgUAoHgw
# GAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGC
# NwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQx
# FgQUQm3VsPvk4vbtwRgKnjHhDdlBDDswDQYJKoZIhvcNAQEBBQAEgYAwBUqfHv+n
# fChB6iwip2jdbQ/z3GX4Nh+y1dDS3a4hZlwoxgY0FWq0GFBL1Oyfjd5Ovy8Ilq3a
# P6YmAkjzNShw4uqXnWNxVQh7iBZmSteageHQhcLoIf5x3+tAISZpo8SWebFRFDWu
# Z1aYcFwSNBNd2RYmpf3gGz1ZTvFGQQe+cw==
# SIG # End signature block
