<#
    Workflow breaks the scoping of EAP
    
    https://technet.microsoft.com/en-us/library/hh847796.aspx

    $ErrorActionPreference
    ----------------------
        Determines how Windows PowerShell responds to a non-terminating
        error (an error that does not stop the cmdlet processing) at the
        command line or in a script, cmdlet, or provider, such as the
        errors generated by the Write-Error cmdlet. 

        You can also use the ErrorAction common parameter of a cmdlet to 
        override the preference for a specific command.
#>

Workflow Test-ErrorActionPreferenceScoping
{
    $ErrorActionPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue

    # Should be swallowed
    Write-Error -Message 'hello'

    # EAP is more specific so it should apply -- expect to see error message but not terminate
    Write-Error -Message 'hello' -ErrorAction Continue

    # EAP is more specific so it should apply -- expect to see error message and terminate
    # not showing the verbose message
    Write-Error -Message 'hello' -ErrorAction Stop
    Write-Verbose -Message 'Should not get here'
}